name: JMA CI Workflow

on:
  workflow_dispatch:

env:
  DOCKER_REPO: jobyjfrancis/devops-bootcamp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_REPO }}:jma-1.0 .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ${{ env.DOCKER_REPO }}:jma-1.0